export enum ACTIVITIES_ACTION_TYPES {
    FETCH_ACTIVITIES_START = 'activity/FETCH_ACTIVITIES_START',
    FETCH_ACTIVITIES_SUCCESS = 'activity/FETCH_ACTIVITIES_SUCCESS',
    FETCH_ACTIVITIES_FAILURE = 'activity/FETCH_ACTIVITIES_FAILURE',
}