# fly.toml file generated for reactivities-app on 2023-01-29T12:58:16+02:00

app = "reactivities-app"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "alexlaer/galactivities:latest"

[env]
ASPNETCORE_URLS="http://+:8080"
Cloudinary__CloudName="dh3fac13y"
Cloudinary__ApiKey="271683484662553"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
